import { useEffect, useState, type FormEvent } from "react";

type Ad = { slot: "hero" | "stream" | "footer"; image_key: string | null; image_alt: string; href: string; enabled: number; imageUrl: string };
const labels: Record<Ad["slot"], string> = { hero: "Hero card", stream: "Long in-page banner", footer: "Footer banner" };

export default function AdManager({ onClose }: { onClose: () => void }) {
  const [authed, setAuthed] = useState(false); const [password, setPassword] = useState(""); const [ads, setAds] = useState<Ad[]>([]); const [note, setNote] = useState("");
  const load = async () => { const response = await fetch("/api/admin/ads", { credentials: "include" }); if (response.ok) { setAds(await response.json()); setAuthed(true); } };
  useEffect(() => { void load(); }, []);
  const login = async (event: FormEvent) => { event.preventDefault(); const response = await fetch("/api/admin/login", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); if (response.ok) { setPassword(""); await load(); } else setNote((await response.json() as { error?: string }).error || "Could not sign in."); };
  const upload = async (slot: Ad["slot"], file?: File) => { if (!file) return; setNote("Uploading banner…"); const form = new FormData(); form.set("image", file); const response = await fetch("/api/admin/upload", { method: "POST", credentials: "include", body: form }); const data = await response.json() as { imageKey?: string; imageUrl?: string; error?: string }; if (!response.ok || !data.imageKey) return setNote(data.error || "Upload failed."); setAds(current => current.map(ad => ad.slot === slot ? { ...ad, image_key: data.imageKey!, imageUrl: data.imageUrl || "" } : ad)); setNote("Banner uploaded. Add its link, then save."); };
  const save = async (ad: Ad) => { setNote("Saving…"); const response = await fetch("/api/admin/ads", { method: "PUT", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ slot: ad.slot, imageKey: ad.image_key, alt: ad.image_alt, href: ad.href, enabled: Boolean(ad.enabled) }) }); const data = await response.json() as { enabled?: boolean; error?: string }; setNote(response.ok ? (data.enabled ? "Saved and live." : "Saved as a black placeholder until a banner and valid link are set.") : data.error || "Save failed."); };
  const update = (slot: Ad["slot"], patch: Partial<Ad>) => setAds(current => current.map(ad => ad.slot === slot ? { ...ad, ...patch } : ad));
  return <div className="mn-backstage" role="dialog" aria-modal="true" aria-label="Midnight Nachos Backstage"><section className="mn-backstage__panel"><div className="mn-backstage__head"><div><span>Backstage</span><h2>Ad manager</h2></div><button onClick={onClose}>Close</button></div>{!authed ? <form onSubmit={login} className="mn-backstage__login"><label>Backstage password<input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)} /></label><button>Open Backstage</button></form> : <div className="mn-backstage__ads">{ads.map(ad => <article key={ad.slot}><div><span>{labels[ad.slot]}</span>{ad.imageUrl ? <img src={ad.imageUrl} alt="" /> : <div className="mn-backstage__blank">Black placeholder</div>}</div><label>Banner image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={event => void upload(ad.slot, event.target.files?.[0])} /></label><label>Destination link<input type="url" placeholder="https://" value={ad.href} onChange={event => update(ad.slot, { href: event.target.value })} /></label><label>Image description<input value={ad.image_alt} onChange={event => update(ad.slot, { image_alt: event.target.value })} /></label><label className="mn-backstage__toggle"><input type="checkbox" checked={Boolean(ad.enabled)} onChange={event => update(ad.slot, { enabled: event.target.checked ? 1 : 0 })} /> Make this ad live</label><button onClick={() => void save(ad)}>Save {labels[ad.slot]}</button></article>)}</div>}<p className="mn-backstage__note" role="status">{note}</p></section></div>;
}
